export enum IngameStatus {
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
  LOBBY = 'LOBBY',
  IN_PROGRESS = 'IN_PROGRESS',
  NEXT_ROUND_SELECT = 'NEXT_ROUND_SELECT',
  INTERMISSION = 'INTERMISSION',
  TERMINATED = 'TERNIMATED',
  PAUSED = 'PAUSED',
}
