export enum RegisterQueueStatus {
  REGISTERED = 'REGISTERED',
  ALREADY_REGISTERED = 'ALREADY_REGISTERED',
  UNREGISTERED = 'UNREGISTERED',
  NOT_REGISTERED = 'NOT_REGISTERED',
  FASTRACK = 'FASTRACK',
  ROOM_FOUND = 'ROOM_FOUND',
}
